### PR TITLE
Update fr

### PR DESCRIPTION
**Pull request by ljdj**
Complete and indented translation in French

### CODE REVIEW

**Comment by iliarostovtsev** [comment]
Look, you should not just move lines from `fr.auto` to `fr` file without checking, improving them. There is no reason in doing it, as there is a [language manager script](https://github.com/webmin/webmin/blob/master/bin/language-manager) that can do all of this automatically.

**Comment by ljdj** [comment]
I prefer to check and indented (as the original file) the auto.fr files and put them on a fr file.

**Comment by iliarostovtsev** [comment]
I will not be able to merge that, unless .auto files are human verified, not just copy pasted.

Thanks.

**Comment by ljdj** [comment]
Auto lines have been checked and modified depending on whether the translation was good or not

**Comment by iliarostovtsev** [comment]
> Auto lines have been checked and modified depending on whether the translation was good or not

.. then we're good. Merci!

**Pull request merged**
