### PR TITLE
replace generic-linux with *-linux in module.info

### PR DESCRIPTION
**Pull request by gnadelwartz**
can confirm that syno-linux is now able to open modules from issue https://github.com/webmin/webmin/issues/745

### CODE REVIEW

**Comment by gnadelwartz** [comment]
hm, could not relove merge conflict jamie pls do it for me ... keep the line with `syno-linux`

**Comment by jcameron** [comment]
Is you aim here to create a new syno-linux OS type?

**Comment by gnadelwartz** [comment]
correct, but instead of adding syno-linux to every module.info I propose to add *-linux instead of every single linux variant.

If you don't like it this way I can simply add syno-linux

**Comment by jcameron** [comment]
I'd recommend adding syno-linux, since if you add *-linux it will cause the modules to appear on systems detected as generic-linux (basically, minimally supported distros).

**Comment by gnadelwartz** [comment]
i ve done this only where generic was supported ... so there should support ... but yes I will do it the requested way and create a new PR

**Pull request closed without merging**
