### PR TITLE
firewall: minimal support for ipset rules

### PR DESCRIPTION
**Pull request by gnadelwartz**
display a description for iptables <tt>--match-set</tt> option in <tt>index.cgi</tt>, lets see if I have time to also display edit ipset content ...
grafik

### CODE REVIEW

**Comment by gnadelwartz** [comment]
pull request #600, OK then I have to implement more for ipset :-).
pls wait unil I'm finished ...

**Comment by chris001** [comment]
Nice.  Support for ip6tables also?

**Comment by gnadelwartz** [comment]
for now only for ipv4

**Comment by gnadelwartz** [comment]
now active ip-sets are displayed by firewall, ready for merging...
next we may allow managing/editing of ip-sets. Since my ip-sets are managed by <tt>fail2ban</tt> its not on my list :-)
grafik

RP #600 , my commit [100](https://github.com/webmin/webmin/pull/600/commits/e69c6699acd4ed332f7f101a6ce4780d5516a208) to webmin

**Comment by jcameron** [comment]
Thanks for the patch!

**Pull request merged**
