### PR TITLE
Add support for forcing encoding using file comment '-*- coding: encoding -*-'

### PR DESCRIPTION
**Pull request by qooob**
https://github.com/qooob/authentic-theme/issues/987

### CODE REVIEW

**Comment by gnadelwartz** [comment]
thanks Ilia for your fast coding :-)

**Comment by qooob** [comment]
You're welcome.

In case you want `vim: encoding ..` to work, you would need to modify regex.

**Comment by gnadelwartz** [comment]
if you used to regex from my link to stackoverflow, it should work already:

`/coding[=:]\s*([-\w.]+)/`

**Comment by qooob** [comment]
It will grab any `coding:` and `coding=` - not good. Needs to be more safe!

**Comment by gnadelwartz** [comment]
it's save when only checking the first two lines and it's a comment. currently you are checking all lines.

`/^\s*#.* coding[=:]\s*([-\w.]+)/`

**Comment by qooob** [comment]
If so, yes. You can go ahead and modify my commit it make your own one instead.

**Comment by jcameron** [comment]
Thanks for the patch! Shall I accept this into Webmin, or is there more work still being done?

**Comment by qooob** [comment]
Yes, and later we'll add it.

**Comment by qooob** [comment]
Okay, Jamie, latest commit is fine. 

It will only look for 3 first lines and also support VIM, because I know some guys with beards that told me once or twice that they use VIM. 😉

**Comment by qooob** [comment]
New pull request but, Jamie, for some reason it was added to this one. Probably because it's opened by me?

I added [hardened filter for checking URL](https://github.com/webmin/webmin/pull/773/commits/d13795190b19d3ffc1138bb4913bd3cad29e250b) before saving. Now, even if opened from desktop mail client, it will not be possible to run a command containing space in it, so running `cmd=ls -lsaZ` will result in the same command but with striped spaces.

Take a look.

**Comment by gnadelwartz** [comment]
hey! I have no beard! even I'm using vi ...

**Comment by qooob** [comment]
There are others with beard! 🤣

**Comment by gnadelwartz** [comment]
this one @swelljoe ?

**Comment by qooob** [comment]
Ha-ha, yeah, that one.. particularly nice guy! 😉

**Pull request merged**
