### PR TITLE
Add jails status and actions 1/2 #1623

### PR DESCRIPTION
**Pull request by iliajie**
This is the first part of PR, which will add jails status and actions.

**Example:**

image

image

### CODE REVIEW

**Comment by iliajie** [comment]
Jamie, do not merge it yet, I will let you know when it's done (later today).

**Comment by iliajie** [comment]
All done! It took some effort.

Alright, alongside with mass operations on a jail, it is also possible to individually remove from a block for a given jail or permanently block given IP address selectively.

image

image

**Comment by jcameron** [comment]
Can you reduce the length of the text on those buttons? They're kind of long .. maybe the second one could be "Block Banned IPs in Selected Jails"

**Comment by iliajie** [comment]
> Can you reduce the length of the text on those buttons?

Done.

**Pull request merged**
