### PR TITLE
Chrizathens patch 1

### PR DESCRIPTION
**Pull request by ChriZathens**

### CODE REVIEW

**Comment by ChriZathens** [comment]
Ok, my lack of proper github knowledge seems to overcomplicate things when it comes to creating new files...

**Comment by jcameron** [comment]
Thanks for the patches!

**Comment by swelljoe** [comment]
I've found it's easier to work with branches, so you can know exactly what will be in the pull request. So, make a branch, make some changes to the branch, commit/push them to your fork, and then make a pull request against that branch.

Once the pull request is merged, you can fetch/merge from upstream, and then once the master branch looks good, you can delete the branch. I often forget to make a branch before I start making commits, though, so it's a habit I'm working on.

**Comment by ChriZathens** [comment]
Hmm, I will check your advice.
I hope I'll manage to figure it out, heh..
Cheers!

**Comment by ChriZathens** [comment]
And just noticed that Lang file for custom module is not complete.
Never mind. At least editing from main branch an existing file is easy, heh.
Will create a pull request tomorrow.

**Pull request merged**
