### PR TITLE
Delete fr.auto

### PR DESCRIPTION
**Pull request by ljdj**
Deletion of the file after updating the file fr English

### CODE REVIEW

**Comment by iliarostovtsev** [comment]
Generally _.auto_ file should be deleted only when human translations were made. Were they made?

**Comment by ljdj** [comment]
Le fichier a été traduit suite à la pull request

**Comment by iliarostovtsev** [comment]
> Le fichier a été traduit suite à la pull request

I am sorry but I haven't seen any changes to `mailboxes/lang/fr`. Perhaps forgot to push it?

**Comment by ljdj** [comment]
Désolé, j'étais pourtant sur de l'avoir push. choses faite.
Pour tous les traductions que j'ai faites, merci de retirer les auto.fr afin de faire gagner de la place sur les serveurs ;)

**Comment by iliarostovtsev** [comment]
.. now I see the that the mail file was committed.

.. to safe your time, you can skip deleting _.auto_ files, as language manager script will automatically diff and fill all files.

**Pull request closed without merging**
