### PR TITLE
fix error the donot detect interfac vlan (ethx.x).

### PR DESCRIPTION
**Pull request by vsc55**
issues #1100

### CODE REVIEW

**Comment by vsc55** [comment]
> 
> 
> Isn't it better to fix this in the `net` module by making `active_interfaces` include vlans?

Yes, but it is my first time with Perl code and I did not want to go deeper into the code.
Let's see if I have a while and I look more deeply.

**Comment by vsc55** [comment]
Hi @jcameron,
First sorry for my English made in Google Translater.

I've been thinking (sometimes I do it and everything 😄) and apart from solving the "active_interfaces" to detect the vlan.

Don't you think it would be nice to let all the interfaces in the system come out, not just the active ones?
It may happen that you want to leave the server preconfigured and that at the time of configuring that interface you do not have it active.
What do you think about the approach?

Best regards.

**Comment by vsc55** [comment]
Fixed the problem of "active_interfaces".
The vlan detection failure occurred when using the "ip" command. With the "ifconfig" command, the vlan is detected correctly.

**Comment by jcameron** [comment]
Thanks!

**Pull request merged**
