### PR TITLE
add -file for pulling single file(s) only

### PR DESCRIPTION
**Pull request by gnadelwartz**
implement @qooob 's request to update specified files only 
implement -nc (noclor) option
some cleanup  and spelling harmonisation

### CODE REVIEW

**Comment by gnadelwartz** [comment]
-file gas to be the last option, every argument after -file is processed as a file name, e.g.

-file */module.info will update all already existing module.info files
-file module/lang/br will pull brasilian lang file, even if it exist or is new

-release:latest -fiile index.cgi will pull index.cgi from latest release, actually 1.870

**Comment by qooob** [comment]
Nice. Will running `-file cpan/*` update all files under cpan only?

**Comment by gnadelwartz** [comment]
yes, all already existing files, but no new files, because * is expanded by shell

**Comment by gnadelwartz** [comment]
hm, jamie was to fast :-), so I have to provide a seperate PR for processing DIRS ...

**Pull request merged**
