### PR TITLE
place buttons also on top of update-packages list #804

### PR DESCRIPTION
**Pull request by gnadelwartz**
see issue https://github.com/webmin/webmin/issues/804

### CODE REVIEW

**Comment by qooob** [comment]
It's not working as not submitting anything.

**Comment by gnadelwartz** [comment]
OK, I'll have a look

**Comment by gnadelwartz** [comment]
now its working for me, give mit a try ...

**Comment by qooob** [comment]
Now we have two `id="refresh"` and two `id="ok"` on the page. This is invalid. We don't need to print `id` at all.

**Comment by gnadelwartz** [comment]
this is from ui_lib ... let me think about it ...

**Comment by gnadelwartz** [comment]
I add `_top` to top buttons names

**Comment by qooob** [comment]
I've also added small margin for the new buttons to look better:
https://github.com/qooob/authentic-theme/commit/e4085ed4ed01eaf638852cf04abed224c542a363

**Comment by jcameron** [comment]
Thanks for the patch!

**Pull request merged**
