### PR TITLE
Add ability to pass browser's client height to the server

### PR DESCRIPTION
**Pull request by iliajie**
This is a take out of the [other PR](https://github.com/webmin/webmin/pull/1904#issuecomment-1545236094) for a better review.

### CODE REVIEW

**Comment by chris001** [comment]
Excellent, looks like solid progress towards responsive web design - [only CSS is needed](https://levelup.gitconnected.com/how-to-create-responsive-website-only-with-css-df4e8a1e8e4e).  CSS detecting the size and resolution of user device screen then dynamically calculate page layout and default font size.

**Comment by iliajie** [comment]
> Excellent, looks like solid progress towards responsive web design - [only CSS is needed](https://levelup.gitconnected.com/how-to-create-responsive-website-only-with-css-df4e8a1e8e4e).

Don't we do it already?

**Comment by chris001** [comment]
> Don't we do it already?

The page layout is responsive, however, if [the font sizes would automatically recalculate for optimum readability](https://www.smashingmagazine.com/2022/01/modern-fluid-typography-css-clamp/), this would be golden.

**Comment by iliajie** [comment]
We will look into it in time, in a major UI upgrade.

**Pull request merged**
