### PR TITLE
Add support for paginated tables in Users and Groups module

### PR DESCRIPTION
**Pull request by iliajie**
Jamie, check this small PR with an example on how we can replace **_old_** search forms, i.e.:

image

.. with the **_new_** pagination table, e.g.:

image

I like paginated table more than the old search form, because search form didn't list any data, which made it more difficult to list through the users and groups.

Please let me know if you have any questions. I have made a nightly Webmin built to include these changes!

### CODE REVIEW

**Comment by iliajie** [comment]
Also, I have just added complete support for the new `ui_paginations` API on Authentic Theme side!

**Comment by jcameron** [comment]
Do you think we need an option to use paginated tables? If the feature works, seems like it could just be on all the time..

**Comment by jcameron** [comment]
I think you should split out the API changes from the Users and Groups module changes - it will be easier to review that way

**Comment by iliajie** [comment]
> Do you think we need an option to use paginated tables? If the feature works, seems like it could just be on all the time.

Yeah, I just fixed that too.

**Comment by iliajie** [comment]
> I think you should split out the API changes from the Users and Groups module changes - it will be easier to review that way

I won't be able to do it, because API changes were not a PR and they were all submitted to the master, and some changes to UI lib were made in this PR by mistake. I meant to commit them to the master directly but by accident committed them here. Redoing it now without conflicts is not possible. Sorry.

**Comment by iliajie** [comment]
> > I think you should split out the API changes from the Users and Groups module changes - it will be easier to review that way
> 
> I won't be able to do it

Maybe I can, hold on.

**Comment by iliajie** [comment]
> > > I think you should split out the API changes from the Users and Groups module changes - it will be easier to review that way
> > 
> > 
> > I won't be able to do it
> 
> Maybe I can, hold on.

Alright, that was done for this PR, and now it only contains changes to `useradmin`. I will remember not to mix changes from now on, as it is too much hassle to fix those..

**Comment by iliajie** [comment]
> I think you should split out the API changes from the Users and Groups module changes - it will be easier to review that way

Alright, check this separate [PR](https://github.com/webmin/webmin/pull/1905) now.

**Comment by iliajie** [comment]
> > I think you should split out the API changes from the Users and Groups module changes - it will be easier to review that way
> 
> Alright, check this separate [PR](https://github.com/webmin/webmin/pull/1905) now.

Also, I have made the new `ui_pagination` API to a [separate PR](https://github.com/webmin/webmin/pull/1906) as well, in case you want to discuss it in more details.

**Comment by jcameron** [comment]
I will merge this, but it looks like there's a merge conflict..

**Comment by iliajie** [comment]
> I will merge this, but it looks like there's a merge conflict.

I don't see any merge conflict. Give it another look please..

**Comment by iliajie** [comment]
This one also look good.

**Pull request merged**
