### PR TITLE
Fix to hide time selection for Linux systems

### PR DESCRIPTION
**Pull request by iliajie**
Fix to hide time format selection for Linux systems.

### CODE REVIEW

**Comment by iliajie** [comment]
Alright, I have reverted the first change in this PR partially, as now I [added @commit/de3b01d](https://github.com/webmin/webmin/commit/de3b01d083eb7020c02573ec28ba15f8eca4e4de) an ability to preserve hidden options values, to make sure that the behavior of a module will not be changed.

**Comment by jcameron** [comment]
Looks mostly reasonable, but see my comments on the other commit.

**Comment by iliajie** [comment]
I commented back on that commit.

**Comment by iliajie** [comment]
Are we merging this?

**Comment by jcameron** [comment]
I still have questions about this config override API ..

**Pull request merged**
