### PR TITLE
fix wrong executable permission on manual.sxw

### PR DESCRIPTION
**Pull request by yangfl**

### CODE REVIEW

**Comment by jcameron** [comment]
Your other commits look good, but why remove Authen-SolarisRBAC-0.1.tar.gz ?

**Comment by yangfl** [comment]
Authen-SolarisRBAC-0.1.tar.gz is already extracted as folder, thus it should be managed by git.

If you don't agree I can modify my commits and leave that file exist (since that's not the main topic of this pr).

**Comment by jcameron** [comment]
The tar.gz file is needed, as it contains a perl module that gets installed by Webmin on Solaris systems.

**Comment by yangfl** [comment]
So what about https://github.com/webmin/webmin/tree/master/acl/Authen-SolarisRBAC-0.1 ?

**Comment by yangfl** [comment]
ok, fixed

**Comment by jcameron** [comment]
Thanks for the patches!

**Pull request merged**
