### PR TITLE
activate update manager, package-updates, passwd and useradmin on synology

### PR DESCRIPTION
**Pull request by gnadelwartz**
image

### CODE REVIEW

**Comment by qooob** [comment]
@gnadelwartz Kay, what browser is that?

**Comment by gnadelwartz** [comment]
vivaldi aka chrome

**Comment by jcameron** [comment]
This patch appears to have changed a bunch of other lines in the module.info files - is that expected?

**Comment by gnadelwartz** [comment]
ah, l have an other idea, all lines with special characters are affected, so its may be because i forced module.info to iso-8859-1. so github displays the lines because of the forced charset ...

**Comment by jcameron** [comment]
Is all you're really trying to do is add syno-linux to the os_support line of the useradmin/module.info file?

**Comment by gnadelwartz** [comment]
yes, in the same hibrid approach lve done it in the "big bang" PR:

- if all 19 linux variants including generic-linux are listed use *-linux
- in all other cases add only syno-linux

beside this I add the config option ipkg for update system

**Comment by gnadelwartz** [comment]
ok, i make a new PR for package-update

**Pull request closed without merging**
