### PR TITLE
Don't filter out URI for trusted source

### PR DESCRIPTION
**Pull request by qooob**
It's important for upcoming 19.09, where right-click and open in new tab, will work correctly with the referre set.

### CODE REVIEW

**Comment by qooob** [comment]
The latest commit of the theme has support for this patch.

Holding `Ctrl` or `Shift` while making a click will also work, just as context-menu/open in new tab.

**Comment by qooob** [comment]
Does it work safe with you?

**Comment by jcameron** [comment]
This looks reasonable - but how are you defining a "dangerous" URL? I don't quite follow what kinds of URLs the regexp is looking for.

**Comment by qooob** [comment]
Regex is looking for spaces primarily. Fir example, opening targeted link from email, will not result into `cmd=rm -rf /`.

**Comment by qooob** [comment]
Oh my, oh my! Just found a bug that breaks Server Index, as it should skip as well:

```Perl
$ENV{'REQUEST_URI'} !~ /link.cgi\/\d+/ &&
```

**Comment by qooob** [comment]
Please test it with the latest commit:
https://github.com/qooob/authentic-theme/commit/dc63db6873b4fa0686011cf3046e7c8e42a61dcf

**Comment by qooob** [comment]
Ref: https://github.com/webmin/webmin/pull/796

**Comment by jcameron** [comment]
Thanks for that fix!

**Pull request closed without merging**
