### PR TITLE
Fix to take out general `websocket` subs to API

### PR DESCRIPTION
**Pull request by iliajie**

### CODE REVIEW

**Comment by jcameron** [comment]
There's a lot going on in this PR ... why move these methods up to the general API? They are specific to the xterm module.

**Comment by iliajie** [comment]
> There's a lot going on in this PR

Doesn't change the logic.

>  why move these methods up to the general API? They are specific to the xterm module.

They are websockets specific and any other module using websockets would do be able to re-use them.

**Comment by jcameron** [comment]
OK, if and when other modules need this functionality, we can move it. We don't even know yet what kinds of paths they'll use. Also, I prefer not to add to the global API until it's needed, as it increases the startup time of other modules.

**Comment by iliajie** [comment]
Alright, fare point. Let me see with that another PR for the port..

**Pull request closed without merging**
