### PR TITLE
Fix not to load Xinha HTML editor, as it breaks Authentic Theme https://github.com/qooob/authentic-theme/issues/977

### PR DESCRIPTION
**Pull request by qooob**
In the future, we should do opposite and load it only for the basic themes, leaving other themes deal with it on their own

### CODE REVIEW

**Comment by jcameron** [comment]
Nice ... however, in future a better solution would be a theme-overridable function that outputs the HTML editor.

**Comment by qooob** [comment]
Maybe, right now I think the best would be is just not to impose any logic on the theme. It's better to make default theme to do exactly what it needs to be done and the theme could decide what and how to load.

However, as long as it;s not hard-code, all would be doable.

**Comment by tiagoadp** [comment]
The problem still happens with 19.08, just tested right now, attached screenshots:

chrome_2018-01-09_10-42-25

chrome_2018-01-09_10-43-28

Goin back to text compose as it is working for now...

**Comment by qooob** [comment]
You need the patch from Webmin:
https://github.com/webmin/webmin/commit/f68039d36030de2452c2f5e23822afc73c43f2f9

**Pull request merged**
