### PR TITLE
Add support for custom redirect URL for Usermin

### PR DESCRIPTION
**Pull request by iliarostovtsev**
It should be possible to define redirect URL for users behind proxies (like from **Virtualmin / Edit Users: Edit User**).

### CODE REVIEW

**Comment by jcameron** [comment]
Where does `redirect_url` that this patch uses get set?

**Comment by iliarostovtsev** [comment]
Nowhere - for now, by editing manually only. That was the question I later asked on the initial support request ticket.

Where do you think it could be added to?

**Comment by jcameron** [comment]
Oh I see. Wouldn't it make more sense for this to be an option in /etc/usermin/config , as it's not really related to miniserv?

**Comment by iliarostovtsev** [comment]
I assumed that as we already have `redirect_host`, `redirect_port` and etc placed in `miniserv.conf`, it would be more intuitive to do the same for `redirect_url`. Yet, do you wish that go to `config`?

**Comment by jcameron** [comment]
Ok, that makes sense

**Comment by iliarostovtsev** [comment]
So now, would that be possible to make all those **`redirect_`** configurable on UI somewhere, to make it more straight forward to use, as now you need to look at the code or search for some deeply buried forum posts?

**Comment by jcameron** [comment]
Yes, I think adding a UI for this would be a good idea ... somewhere at Webmin -> Usermin Configuration.

**Comment by iliarostovtsev** [comment]
What about Webmin? Could you be more specific where in Webmin/Usermin Configuration it should be added?

**Comment by jcameron** [comment]
I was thinking on the **Web Server Options** page?

**Comment by iliajie** [comment]
> I was thinking on the **Web Server Options** page?

Jamie, please have a look, as this has been implemented on this commit - https://github.com/webmin/webmin/commit/086bd55ddd22a35a1e8344cbe22dde73d0ed48f5.

Almost all looks good to me, and the only thing I'm not certain about is text labels as **Internal redirect URL overrides** and **Post-login switch redirect URL** (only for **Usermin Configuration: Web Server Options**):

image

Feel free to reword those labels.

**Comment by jcameron** [comment]
This looks fine to me - thanks!

**Pull request merged**
