### PR TITLE
Simply replace Gray Framed with Virtualmin Framed theme

### PR DESCRIPTION
**Pull request by iliajie**
For the start, let's just replace Gray Theme with Virtualmin Framed Theme. It will just work for users with the same setup.

`virtualmin-server-theme` repo can be archived.

### CODE REVIEW

**Comment by jcameron** [comment]
This is a big big change .. let's not do it now when we have multiple other large changes in flight.

**Comment by iliajie** [comment]
Alright, fair point.

We can do it with 1.996. Although, the change is not changing anything for the user. It's the same theme from the user's config perspective.

**Comment by jcameron** [comment]
Yeah, let's look into this after we do a release

**Comment by iliajie** [comment]
I assume not yet or 1.997 is good for it?

**Comment by jcameron** [comment]
Let's see if we need a new bugfix release first on top of 1.996

**Comment by iliajie** [comment]
Yeah, I think we do need 1.997 have things done right and have it released to Virtualmin users finally.

I think this can go to 1.998 if you're afraid it may break something.

**Comment by jcameron** [comment]
Yeah let's put this in 1.998.

**Comment by iliajie** [comment]
Great, I'm fine with this!

**Comment by iliajie** [comment]
Are we putting this to 1.998?

**Comment by jcameron** [comment]
If we need 1.998 to fix bugs in 1.997, let's hold off on this. I want to get a release out that's bug-free

**Comment by iliajie** [comment]
Alright, makes perfect sense. Let's put it off until 1.999.

Also, where do you potentially see bugs in here, so I could try to prevent any issues before we later add it to 1.999?

**Comment by jcameron** [comment]
I just assume that all large changes will have bugs :-)

**Comment by iliajie** [comment]
Okay! :-)

**Comment by iliajie** [comment]
This can be merged.

**Comment by jcameron** [comment]
Did you also apply this fix : https://github.com/virtualmin/virtual-server-theme/commit/958a961b689117b35195636f1403dd1823811c89

**Comment by iliajie** [comment]
I ran tests with builds and it worked just fine for all users that previously had either `blue-theme` or `gray-theme` set.

**Pull request merged**
