### PR TITLE
ajdust filemin german translations

### PR DESCRIPTION
**Pull request by gnadelwartz**
Adjust german filemin translations to fit better to context and authentic-theme translations

### CODE REVIEW

**Comment by gnadelwartz** [comment]
how do you keep lang/de and lang/de.UTF-8 in sync?
qoob handles this by linking lang/de to lang/de.UTF-8

**Comment by jcameron** [comment]
Thanks! Currently the UTF-8 files are auto-generated

**Comment by gnadelwartz** [comment]
hm, did I edit the wrong file, because I changed the de.UTF-8 file directly?

**Comment by jcameron** [comment]
Can you also make the same change to the `de` file?

**Pull request merged**
