### PR TITLE
language code for Latvian

### PR DESCRIPTION
**Pull request by Kleofass**

### CODE REVIEW

**Comment by jcameron** [comment]
It seems like this patch re-ordered the whole file ... is that expected?

**Comment by Kleofass** [comment]
A-Z order - just about a clean design. If it affects a function, then we can leave the old content.

**Comment by qooob** [comment]
It's never good idea to sort things like that as it gets very difficult to watch changes.

**Comment by Kleofass** [comment]
Ok. I will delete this request.

**Pull request closed without merging**
