### PR TITLE
Updated Chinese translations

### PR DESCRIPTION
**Pull request by leangjia**
Updated Chinese translations acl lang zh.

### CODE REVIEW

**Comment by iliajie** [comment]
杜哥，您好!

Thanks for your patches! They're highly appreciated!

One thing, though — you need to delete the `zh.auto` files (machine translated) for the strings that were added to the `zh` (human translated) files.

Could you do that?

**Comment by leangjia** [comment]
@iliajie 您好！Thanks for your reminder.I will fix it.

**Comment by iliajie** [comment]
Alright, thanks! Please let me know when it's ready.

One last thing — please don't rename the PR after it's created, as it breaks threading in email clients. In fact, your title doesn't need to reflect the translated modules; you can just call it "Updated Chinese translations," "Updated Chinese translations part 2," or whatever you like.

**Comment by leangjia** [comment]
@iliajie Have a good day!

**Comment by iliajie** [comment]
Excellent! Thanks!

**Pull request merged**
