### PR TITLE
`mode 1` endlessly better looking, right?

### PR DESCRIPTION
**Pull request by qooob**

### CODE REVIEW

**Comment by jcameron** [comment]
Maybe .. if you have only a few commands, it makes sense to show them right on the first page.

**Comment by qooob** [comment]
To show what on the first page? List of commands?

**Comment by qooob** [comment]
I, by the way, added (in v. 14.01) automatic syntax highlight detection, now editing files in _Webmin_ with `Custom Commands` is absolute pleasure! Please try! ;)

**Comment by jcameron** [comment]
I mean the command buttons and their inputs.

**Comment by qooob** [comment]
Jamie, I would like to improve where I can and this is why I continue this discussion, I didn't understand to what you are trying to say at all. Makes no sense to me. What do you mean by `command buttons and their inputs.`? Sorry.

**Comment by jcameron** [comment]
What I mean is the command parameters, like the "User to check" box in this screenshot ..
screen shot 2015-08-01 at 3 13 16 pm

**Comment by qooob** [comment]
Alright, Jamie! I will take a close look!

**Pull request closed without merging**
