### PR TITLE
Add improvement to repos setup script

### PR DESCRIPTION
**Pull request by iliajie**
Hello Jamie,

Today, I worked on improving our CI development repositories by switching to a structured layout for Debian-based repositories instead of the flat style, i.e.:

```
deb [signed-by=/usr/share/keyrings/debian-webmin-developers.gpg] https://download.webmin.dev webmin main
```

instead of (it will still work for compatibility reasons):

```
deb [signed-by=/usr/share/keyrings/debian-webmin-developers.gpg] https://download.webmin.dev ./
```

This required changes to the repository setup script, so I took the chance to rework it as well.

The new script consolidates all the existing ones into a single unified script, which can be used to set up both stable and unstable repositories. This makes it easier to maintain and support.

Once merged, the link at https://download.webmin.com/download will need to be updated to the new script. I’ll handle the update for https://download.webmin.dev as well.

I’ve tested it thoroughly, so just a quick check must be enough. Everything is working perfectly on my end, and the script is POSIX-compatible too.

### CODE REVIEW

**Comment by jcameron** [comment]
Wait does this mean that the old repo paths will no longer be valid, and all users will need to upgrade to the new paths?

**Comment by iliajie** [comment]
> Wait does this mean that the old repo paths will no longer be valid, and all users will need to upgrade to the new paths?

No, no. It will work for the existing configuration, but all new configurations will be set up in a better way.

**Comment by jcameron** [comment]
The diff is hard to read on this PR, as it looks like one file is being entirely deleted and a new one created?

**Comment by iliajie** [comment]
Yes, there is no active diff; I just reworked the entire script.

**Comment by jcameron** [comment]
When you say : 

> Once merged, the link at https://download.webmin.com/download will need to be updated to the new script. I’ll handle the update for https://download.webmin.dev/ as well.

What does that mean exactly? Will the format of repo directory need to be changed?

**Comment by iliajie** [comment]
> What does that mean exactly? Will the format of repo directory need to be changed?

No, it's just a repo-setup script link. The repos will work as before.

**Comment by jcameron** [comment]
Oh ok! Looks good then ...

**Comment by iliajie** [comment]
Thanks for merging it! Please update download.webmin.com to use the new link and a filename.

**Comment by jcameron** [comment]
Do you mean this collapsible section? 

image

If so, what's the new URL?

**Comment by iliajie** [comment]
Yes, the new script name is `webmin-setup-repo.sh`. It should be replaced in both cases (in the screenshot).

**Comment by jcameron** [comment]
Ok will do!

**Pull request merged**
