### PR TITLE
Links2button real changes - just for couriosity

### PR DESCRIPTION
**Pull request by gnadelwartz**
just for couriosity, same PR showing only the REAL changes after majordomo changes are merged.
as you can see it stqys as simple like before, only changed from ui-link to ui-input and everything floating in one cell. only the scrit at the end is something that souldbe not there, but I liked to showcase how it can be done in the theme 😋

can be dissmised without further notice

### CODE REVIEW

**Comment by jcameron** [comment]
Nice, but I think I'd prefer sticking with ui_link

**Comment by gnadelwartz** [comment]
thanks!

**Comment by gnadelwartz** [comment]
totally unrelaed question:
I use vsftp. In module section you are listed as maintianer of a vsftpmodule for virtualmin, is it only for virtualmin really? all other vsftp modules seems orphaned, site no more existing.

**Comment by swelljoe** [comment]
It is not a general purpose UI for vsftpd, it just provides Virtualmin hooks so that it can turn off and on the bits a virtual domain in Virtualmin would need to provide FTP features. 

So, yeah, it really is just for Virtualmin and would not be useful (or even do anything) without Virtualmin.

**Comment by gnadelwartz** [comment]
OK the I will pull one of the orphaned versions out from archive and see if they are working

**Pull request closed without merging**
