### PR TITLE
Change: Do not list Legacy Theme in dropdown

### PR DESCRIPTION
**Pull request by iliarostovtsev**
I think listing Legacy Theme (Old Webmin Theme) must not be an option

### CODE REVIEW

**Comment by jcameron** [comment]
What if somehow a user actually has the old theme selected though?

**Comment by iliarostovtsev** [comment]
Then, by visiting one of those pages there will simply be no option for Old Theme, and to save the form a user would need to either select Gray or Authentic Theme.

**Comment by iliarostovtsev** [comment]
Legacy Theme is a fall back solution only. We don't expect anyone selecting it.

**Comment by jcameron** [comment]
In that case, at least set the 5th param of ui_select to 1 (the "missing" flag), so that the user doesn't get an unexpected theme change.

**Comment by iliarostovtsev** [comment]
> In that case, at least set the 5th param of ui_select to 1 (the "missing" flag), so that the user doesn't get an unexpected theme change.

That wouldn't work as expected but this commit does it - https://github.com/webmin/webmin/pull/1452/commits/4882e980f6ddd949d9efb6bae41a9389c1e3cda5

The users with Legacy Theme selected will have it as an option. Other users won't. I think it's all ready.

**Comment by jcameron** [comment]
Looks good, thanks!

**Pull request merged**
