### PR TITLE
Fix Webmin installation issues

### PR DESCRIPTION
**Pull request by iliajie**
Ref.: https://github.com/webmin/webmin/issues/2022#issuecomment-1755745916

### CODE REVIEW

**Comment by iliajie** [comment]
I have been running today more deep tests with clean installs. CentOS 6 installation still ends up without `/etc/init.d/webmin` file. What can be wrong?

**Comment by jcameron** [comment]
Where in setup.sh should this be happening? Seems like it should be here, but that block is empty : https://github.com/webmin/webmin/blob/master/setup.sh#L799

**Comment by iliajie** [comment]
> Where in setup.sh should this be happening? Seems like it should be here, but that block is empty : https://github.com/webmin/webmin/blob/master/setup.sh#L799

Hm, indeed. I thought we called `init/updateboot.pl` for this purpose? We're calling it, right?

**Comment by jcameron** [comment]
Isn't it atboot.pl that does it?  Also, is this failing for an RPM or tar.gz install?

**Comment by iliajie** [comment]
Alright, it's all fixed on the latest commits.

Although, I think we also need to fix a problem when Webmin and Usermin doesn't open default 10000 and 20000 firewall ports upon installation ..

**Comment by jcameron** [comment]
Please open a separate ticket for that, because it should happen if a supported firewall is in use..

**Pull request merged**
