### PR TITLE
convert usermin module config links to floating buttons

### PR DESCRIPTION
**Pull request by gnadelwartz**
As noticed here https://github.com/qooob/authentic-theme/issues/756 
 its hard to touch on the correct link in lists of links on tablet/phone.
I found two areas in webmin which are difficult to use on touch screens ...

to solve this I converted one of them from links in table to floating buttons, this is like it looks before and after now:
grafik

grafik

grey framed theme:
grafik

floating on big and small screen
grafik

grafik

If you like it, I can convert also "read user mail" ...

### CODE REVIEW

**Comment by qooob** [comment]
It's better to do this globally in the theme rather than on the module side, I think.

I have your feature request. I will do it a bit later.

**Comment by gnadelwartz** [comment]
Im with you to have a general solution by the theme, but on the other hand its then authentic-theme only. converting the links in the module itself change it for all themes, i.e for grey theme as shown.

a combined solution can be to remove the  css for formating and icon and let the theme decide how to display the buttons.

**Comment by qooob** [comment]
From your screenshot back button looks broken.

Kay, sorry but I'm personally against adding presentation logic to modules like this.

**Comment by gnadelwartz** [comment]
thanks for pointing out, didn't notice the canged back button! sorry

**Comment by jcameron** [comment]
I'm also in favor of doing this in the theme. The module code just creates a grid of links with `ui_link` and `ui_grid_table`

**Comment by gnadelwartz** [comment]
ok, ill keep it in my private tree until its done.

BTW: you accepted my other PR, shoudnt the the duplicate changeset vanish from this PR?

**Comment by qooob** [comment]
It's been fixed on the theme side.

**Pull request closed without merging**
