### PR TITLE
To compliy with upcomming Authentic release 18.00

### PR DESCRIPTION
**Pull request by qooob**
Respecting language forms is nice.

### CODE REVIEW

**Comment by jcameron** [comment]
I assume this won't break systems running the older theme version?

**Comment by qooob** [comment]
No, it will just print same stuff.

**Comment by qooob** [comment]
Double checked - all is fine.

**Comment by qooob** [comment]
Ahh. Older Authentic Themes... Hmm.. Let me think..

No, it will just print nice on the first load and then print old/incorrect stuff after first XHR.

**Comment by qooob** [comment]
Actually, it will not print old stuff. It will print properly right away..

**Pull request merged**
