### PR TITLE
Add support for displaying service ports/protocols

### PR DESCRIPTION
**Pull request by iliajie**
This improvement will make it clear what ports and protocols are implied for each service.

**Example:**

image

### CODE REVIEW

**Comment by iliajie** [comment]
It will look like this when editing/adding a service. It will also be possible to quickly filter/search for needed port with a dropdown:

image

**Listing with for services with multi ports:**
image

**Comment by jcameron** [comment]
Looks good, but can you change the main page UI to format the port like `ssh (22)` instead of `ssh:22` ?

**Comment by iliajie** [comment]
> Looks good, but can you change the main page UI to format the port like `ssh (22)` instead of `ssh:22` ?

Yeah, why not. Hold on..

**Comment by iliajie** [comment]
Done.

**Comment by jcameron** [comment]
Thanks for the patch!

**Pull request merged**
