### PR TITLE
Spam: implement edit of amavisd.conf parameters for Spam classification and filtering

### PR DESCRIPTION
**Pull request by gnadelwartz**
new cgi's to edit amavis spam parameters:

- new cgi's `edit_amavisd.cgi` and `save_amavisd.cgi`
- new `spam-amavis-lib.pl` for read and save amavis config values
- convert warnings and info messages to `ui_alert_box`

### CODE REVIEW

**Comment by gnadelwartz** [comment]
image

image

image

**Comment by jcameron** [comment]
Nice .. is this ready to merge?

**Comment by gnadelwartz** [comment]
yes

**Comment by gnadelwartz** [comment]
image

**Comment by gnadelwartz** [comment]
@jcameron  can you please merge? 
I have a bunch of changesets I want to push to my spam branch which are not ready for production...

**Comment by qooob** [comment]
If I understand correctly, your commit should stay as it is, no matter if you push anything to the repo afterwards or not.

**Comment by gnadelwartz** [comment]
if I push new changes they will appear also in an open PR:

Add more commits by pushing to the spam branch on gnadelwartz/webmin.

**Comment by jcameron** [comment]
Ok I will merge now ..

**Pull request merged**
