### PR TITLE
fix usermin and other problems in update-from-repo

### PR DESCRIPTION
**Pull request by gnadelwartz**
there seems to be may broken symlinks in usermin ...

### CODE REVIEW

**Comment by jcameron** [comment]
The current Usermin code in github assumes that it's checked out into a directory called `useradmin` that has the Webmin code in a `webadmin` directory at the same level.

**Comment by gnadelwartz** [comment]
its done this way by my script and most symlinks are resolved this way, but nevertheles it get some error messages from cp -r within makedist.pl.

nevertheless this pr does only fix an internal issue when checking out the source and supressing the error messages only.

**Comment by jcameron** [comment]
Ok .. is this fix ready to merge then?

**Comment by gnadelwartz** [comment]
let me first check if the not resolved symlinks are a problem of my script or really not resolve able.

BTW: do you run makedist.pl from within useradmin or as useradmin/makedist.pl? l run it from within ...

**Comment by qooob** [comment]
Kay, didn't you think of splitting regular `-linux`, `-freebsd` update script and `-synology` one?

When running `update-from-repo.sh` and in case it's Synology OS, you could pull/load some extra stuff and then go, without fear of breaking anything for `-linux` distros?

**Comment by gnadelwartz** [comment]
let's check its my script ...

- correct dirs? seems OK

``` 
rrr:/usr/libexec/usermin/.~files # ls -l .

drwxr-xr-x 1 root root 3878 19. Feb 15:35 useradmin
drwxr-xr-x 1 root root 6138 19. Feb 15:35 webadmin
```

- does the missing symlinks errors appear also on manual invocation? YES

```
rrr:/usr/libexec/usermin/.~files/useradmin # perl makedist.pl `cat version`

Adding top-level files
Adding module cshrc
Adding module file
cp: cannot stat 'file/file.jar': No such file or directory
Adding module forward
...
Adding module mysql
cp: cannot stat 'mysql/config-redhat-linux-25.0-ALL': No such file or directory
Adding module procmail
cp: cannot stat 'procmail/down.cgi': No such file or directory
cp: cannot stat 'procmail/edit_env.cgi': No such file or directory
cp: cannot stat 'procmail/edit_recipe.cgi': No such file or directory
cp: cannot stat 'procmail/images': No such file or directory
cp: cannot stat 'procmail/index.cgi': No such file or directory
cp: cannot stat 'procmail/lang': No such file or directory
cp: cannot stat 'procmail/procmail-lib.pl': No such file or directory
cp: cannot stat 'procmail/save_env.cgi': No such file or directory
cp: cannot stat 'procmail/save_recipe.cgi': No such file or directory
cp: cannot stat 'procmail/up.cgi': No such file or directory
Adding module chfn
...
Adding module postgresql
cp: cannot stat 'postgresql/config-redhat-linux-24.0-ALL': No such file or directory
cp: cannot stat 'postgresql/config-suse-linux-9.1-ALL': No such file or directory
Adding module spam
...
Adding module mailcap
cp: cannot stat 'mailcap/delete.cgi': No such file or directory
cp: cannot stat 'mailcap/edit.cgi': No such file or directory
cp: cannot stat 'mailcap/images': No such file or directory
cp: cannot stat 'mailcap/index.cgi': No such file or directory
cp: cannot stat 'mailcap/lang': No such file or directory
cp: cannot stat 'mailcap/log_parser.pl': No such file or directory
cp: cannot stat 'mailcap/mailcap-lib.pl': No such file or directory
cp: cannot stat 'mailcap/save.cgi': No such file or directory
Adding module blue-theme
```

- check manually for not resolved symlinks ...

```
rrr:/usr/libexec/usermin/.~files/useradmin # ll file/file.jar
lrwxrwxrwx 1 root root 28 Feb 19 15:35 file/file.jar -> ../../webadmin/file/file.jar
rrr:/usr/libexec/usermin/.~files/useradmin # ll file/../../webadmin/file/file.jar
ls: cannot access 'file/../../webadmin/file/file.jar': No such file or directory

rrr:/usr/libexec/usermin/.~files/useradmin # ll mysql/config-redhat-linux-25.0-ALL
lrwxrwxrwx 1 root root 54 Feb 19 15:35 mysql/config-redhat-linux-25.0-ALL -> /usr/local/webadmin/mysql/config-redhat-linux-25.0-ALL

rrr:/usr/libexec/usermin/.~files/useradmin # ll procmail/down.cgi
lrwxrwxrwx 1 root root 37 Feb 19 15:35 procmail/down.cgi -> /usr/local/webadmin/procmail/down.cgi

rrr:/usr/libexec/usermin/.~files/useradmin # ll mysql/config-redhat-linux-25.0-ALL
lrwxrwxrwx 1 root root 54 Feb 19 15:35 mysql/config-redhat-linux-25.0-ALL -> /usr/local/webadmin/mysql/config-redhat-linux-25.0-ALL

rrr:/usr/libexec/usermin/.~files/useradmin # ll procmail/down.cgi
lrwxrwxrwx 1 root root 37 Feb 19 15:35 procmail/down.cgi -> /usr/local/webadmin/procmail/down.cgi

rrr:/usr/libexec/usermin/.~files/useradmin # ll postgresql/config-redhat-linux-24.0-ALL
lrwxrwxrwx 1 root root 59 Feb 19 15:35 postgresql/config-redhat-linux-24.0-ALL -> /usr/local/webadmin/postgresql/config-redhat-linux-24.0-ALL

rrr:/usr/libexec/usermin/.~files/useradmin # ll mailcap/delete.cgi
lrwxrwxrwx 1 root root 38 Feb 19 15:35 mailcap/delete.cgi -> /usr/local/webadmin/mailcap/delete.cgi

```
- got it, all of the errors but the first are absolute symlinks witch does not bother in Jamie's setup, in all other locations they are broken ...

**Comment by gnadelwartz** [comment]
@jcameron  you can merge this PR its not my scripts fault. May be you like to fix these absolute symlinks to relative ones ...

**Comment by gnadelwartz** [comment]
UPS, wrong branch ...

**Comment by gnadelwartz** [comment]
`git log -1` seems not to work everywhere.

Fix: use current date if git log -1 does return nothing ... see https://github.com/qooob/authentic-theme/issues/1001

**Comment by jcameron** [comment]
I'm about to do new webmin and usermin releases. Is this patch ready to merge?

**Comment by gnadelwartz** [comment]
yes

**Comment by jcameron** [comment]
Great, thanks!

**Pull request merged**
