### PR TITLE
Fix size sorting issues

### PR DESCRIPTION
**Pull request by rostovtsev**
This [issue 57297](https://www.virtualmin.com/node/57297) and other, was there for quite a long time. Now, it can be sorted just fine for all languages, even though other other data types present. I made it better, than using _dataTables_ plugins.

Ref.: https://github.com/authentic-theme/authentic-theme/commit/3de119a732d180c68e5ef76962b1bab4fe4413ac

### CODE REVIEW

**Comment by jcameron** [comment]
Should this be limited to just the authentic theme, like the similar date <span> change was? Also, it should be done only when viewed on the web, to prevent this <span> from appearing in emails.

**Comment by rostovtsev** [comment]
Oh, alright. Then you want to let this accessible from the theme as `theme_nice_size`?

**Comment by rostovtsev** [comment]
It works with other themes as well. Just maybe leaving it for all as it is?

**Comment by webmin** [comment]
Ok .. but we will need to turn this off when the function is not called on the web.

**Comment by webmin** [comment]
Maybe it's best to do it like this : https://github.com/webmin/webmin/commit/82dca72335842cc50ff8d1037c62e311f7ce67ca

**Comment by rostovtsev** [comment]
Yes, yes, I remember perfectly how  it's done. I will do it. 😉

**Comment by rostovtsev** [comment]
Yes, sure. I'll add it on the theme side. I got your point, for the future I will do that.

**Pull request closed without merging**
