### PR TITLE
It has so many beautiful modules, calling it `Others` not very cool. …

### PR DESCRIPTION
**Pull request by qooob**
…I think `Tools` suites perfectly.

### CODE REVIEW

**Comment by jcameron** [comment]
While I agree that "Others" isn't the best name, so many users are used to it now that renaming it would be confusing.

**Comment by qooob** [comment]
Ehh, ok. I understand. Let's do it on Webmin 2.0.

**Comment by singhdd93** [comment]
I think it should be named Other/Tools in next release and then shifted to Tools in a major update

**Comment by qooob** [comment]
+1

**Comment by qooob** [comment]
I still think it should be called tools.

Confusion will go away after using it once.

**Pull request closed without merging**
