### PR TITLE
Fixed Simplified Chinese translation issues

### PR DESCRIPTION
**Pull request by kasuganosoras**
Updated Simplified Chinese translation.

### CODE REVIEW

**Comment by iliarostovtsev** [comment]
Thank you very much! For the future PRs (if you do any) all human translated strings must be put to `zh` file, while `zh.auto` file be deleted.

**Comment by kasuganosoras** [comment]
Thanks. I see. : )

**Comment by iliarostovtsev** [comment]
@kasuganosoras Meiko, this should be the right way of doing it - https://github.com/webmin/webmin/commit/5dc2ec2b46273822092412a677625be67d365154

**Comment by kasuganosoras** [comment]
ok, I will do this in the next localization update.

**Pull request merged**
