### PR TITLE
Fix to work-around the bug with time offsets #552

### PR DESCRIPTION
**Pull request by iliaross**

### CODE REVIEW

**Comment by jcameron** [comment]
This doesn't seem like a good idea! We should always store Unix times in GMT, and if there's any change needed for display purposes that should happen in make_date.

**Comment by iliajie** [comment]
> This doesn't seem like a good idea! We should always store Unix times in GMT, and if there's any change needed for display purposes that should happen in make_date.

The problem is not in `make_date` though, right?

**Comment by jcameron** [comment]
Isn't it? The time() function returns a Unix time integer that should be the same regardless of which timezone the system is in, unless the user's machine time is set wrong.

**Comment by iliajie** [comment]
> Isn't it? The time() function returns a Unix time integer that should be the same regardless of which timezone the system is in, unless the user's machine time is set wrong.

Well, this is super confusing. I now can also see that `time()` returns the same timestamp regardless of where it's called. Before it was't the case whatsoever! I will have to take another look.

Also, the incorrect time is displayed in **Recent Logins** accordion only, and both timestamps are run through `make_date` sub, and the issue happens only for the given time zone. Perhaps, when run via CLI it changes something? I will have to check again!

**Pull request closed without merging**
