### PR TITLE
Change webmin/usermin detection in update.sh

### PR DESCRIPTION
**Pull request by gnadelwartz**
Until now I check for dirnames webmin and usermin, but the name of the installtion dir can be anything different.

So I changed the detection of webmin / usermin  by checking for existence of typical files:

- setup.sh and miniserv.pl not present => no webmin/usermin installation
- existence of usermin-init and uconfig.cgi => usermin detected

### CODE REVIEW

**Comment by gnadelwartz** [comment]
@iliaross  may be you what to change it simmilar in your update script also ...

**Comment by qooob** [comment]
@gnadelwartz It's not needed in my setup. Each script runs individually and doesn't care about anything in this regard.

**Comment by gnadelwartz** [comment]
you use also $PROD based on dirname to display messages:

PROD=${DIR##*/}

**Comment by qooob** [comment]
I see what you mean. Thanks. I didn't know that the path could be `/webmin/target/bin` - this is very odd.

**Pull request merged**
