### PR TITLE
Add support for better HTML handling in email replies

### PR DESCRIPTION
**Pull request by iliajie**
Jamie, hey! Please check this PR.

  1. It enables a better HTML handling when replying to emails
  2. Adds a new Quill HTML editor and drops Xinha

mailboxes-html-replies

### CODE REVIEW

**Comment by jcameron** [comment]
What's the license like on this new HTML editor? Can we freely include it with Webmin?

**Comment by iliajie** [comment]
> What's the license like on this new HTML editor? Can we freely include it with Webmin?

Yes, it's **BSD 3-Clause** license.

**Comment by swelljoe** [comment]
And, it's very actively maintained by huge companies. https://github.com/quilljs/quill

**Comment by iliajie** [comment]
@jcameron Jamie, it is all finished now!

**Comment by jcameron** [comment]
Merged! I will try this out and see how it goes ...

**Comment by iliajie** [comment]
I have a small summary about how well and precise emails are rendered now. It is displayed identically great in Google Mail, Proton Mail or Thunderbird! The only difference (which is a separate issue), that Google Mail doesn't display our emails which have inline pictures.

Anyway, below you can find the conversation between me and myself. Look how everything is well formatted across the whole conversation with Google Mail:

#### Sending side (Webmin)
image
image

#### Receiving side (Google Mail)
imageimage

#### Replying (Google Mail)
image

#### Replying after receiving (from Google Mail)

image

**Comment by iliajie** [comment]
> Merged! I will try this out and see how it goes ...

Thanks, let me know if anything goes wrong!

**Comment by jcameron** [comment]
Looks pretty good! I did see two issues though, when using the old theme : 

1 - An image in the quoted reply wasn't shown

2 - There's a big gap above the quoted message (above the ... icon)

image

**Comment by iliajie** [comment]
> Looks pretty good! 

Thanks, I'm glad you liked it! I put a lot of time into it!

> 2 - There's a big gap above the quoted message (above the ... icon)

This can be fixed. It happens because I set the minimum editor container height to 220px. You don't like it? We need to have a minimum editor height? Do we need a resize dragger?

> An image in the quoted reply wasn't shown

I assume you received a reply from Google Mail? if so this is (for now) expected. Although it works if sent across Webmin/Usermin or Proton mail or Thunderbird.

image


The fix for Google Mail should be somewhere in `send_mail.cgi` fully setting image content type in HTML message, e.g.:
```
--0000000000006a00f005fee34ca5--
--0000000000006a00f105fee34ca6
Content-Type: image/png; name="image.png"
Content-Disposition: attachment; filename="image.png"
Content-Transfer-Encoding: base64
X-Attachment-Id: ii_lja9l2wk0
Content-ID: <ii_lja9l2wk0>

iVBORw0KGgoAAAANSUhEUgAAAKIAAABGCAYAAABPJ0+PAAAKq2lDQ1BJQ0MgUHJvZmlsZQAASImV
lwdQU+kWgP97bzoJLSEUKaE3QToBpITQAihIBxshCSGUEANBxI4sroANFRGs6CpFwVUpslZEsbAo
KnZdkEVEWRcLoqLyLjCE3X3z3pt3Zs6c7557/nPO/8/9Z84FgKLMlUhSYWUA0sSZ0jB/b0ZMbBwD
```

.. and referencing it using `[image: image.png]` (considering this example).

**Comment by jcameron** [comment]
Actually this was an email from Usermin to Usermin, so Gmail wasn't involved.

**Comment by iliajie** [comment]
> Actually this was an email from Usermin to Usermin, so Gmail wasn't involved.

Oh, I see now! We already know how to create image reference in Usermin. I am surprised that `send_mail.cgi` in Webmin isn't the same as in Usermin.

This fix to this problem is here https://github.com/webmin/webmin/commit/43dc4a479e3c1147456dad4e911e1430185d0138. All good for this one?

**Comment by iliajie** [comment]
Also, check [this PR](https://github.com/webmin/webmin/pull/1935), it addresses this issue for Webmin.

**Comment by iliajie** [comment]
Also, I have just fixed a bug to correctly set styling for our HTML emails, i.e. for `blockquote`, `p` and other tags for which we define stylings .. so, Webmin PR is the last obstacle ..

**Comment by jcameron** [comment]
Thanks, looks good now!

**Pull request merged**
